---
#

- name: "Configure network devices"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    test_var: "test"

  tasks:
    - import_role:
        name: common

    - import_role:
        name: device/access-point

    - import_role:
        name: device/router

    - import_role:
        name: device/firewall

#    - import_role:
#        name: server/dhcp
#
#    - import_role:
#        name: server/dns
#
#    - import_role:
#        name: server/ntp
#
#    - import_role:
#        name: server/vpn

